export const dataCamiones =  [
    {
        vehiculo: 154 ,
        nombreCompañia: 'Elbira',
        horarios: 'e 20:00 - s 12:00',
        carga: 124,
        galpon: 2,
    },
    {
        vehiculo: 190 ,
        nombreCompañia: 'Ramon',
        horarios: 'e 20:00 - s 12:00',
        carga: 950,
        galpon: 2,
    },
    {
        vehiculo: 186 ,
        nombreCompañia: 'Jere',
        horarios: 'e 20:00 - s 12:00',
        carga: 800,
        galpon: 2,
    },
    {
        vehiculo: 146 ,
        nombreCompañia: 'Shamp',
        horarios: 'e 20:00 - s 12:00',
        carga: 560,
        galpon: 2,
    },
    {
        vehiculo: 145 ,
        nombreCompañia: 'Short',
        horarios: 'e 20:00 - s 12:00',
        carga: 800,
        galpon: 2,
    },
    {
        vehiculo: 1172 ,
        nombreCompañia: 'Tesk',
        horarios: 'e 20:00 - s 12:00',
        carga: 1200,
        galpon: 2,
    },
    {
        vehiculo: 19 ,
        nombreCompañia: 'Tesk',
        horarios: 'e 20:00 - s 12:00',
        carga: 120,
        galpon: 2,
    },
    {
        vehiculo: 13 ,
        nombreCompañia: 'Sesk',
        horarios: 'e 20:00 - s 12:00',
        carga: 980,
        galpon: 2,
    },
    {
        vehiculo: 49 ,
        nombreCompañia: 'Resk',
        horarios: 'e 20:00 - s 12:00',
        carga: 200,
        galpon: 2,
    }, 
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },  
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
    {
        vehiculo: "-",
        nombreCompañia: '-',
        horarios: '-',
        carga: '-',
        galpon: '-',
    },
] 
